using System.Text;

namespace RockBot.Observation;

/// <summary>
/// Deterministic template renderer for observation state. Produces the
/// markdown body that is written to the target's <c>OutputMarkdownPath</c>
/// each phase 2 run. No LLM polish — that would re-introduce the rewriting
/// risk the framework's anti-hallucination defenses are designed to avoid.
/// </summary>
internal static class MarkdownRenderer
{
    /// <summary>
    /// Renders the markdown body for a target. <paramref name="renderedAt"/>
    /// is included in the header so the operator can spot stale output at
    /// a glance.
    /// </summary>
    public static string Render(
        ObservationTarget target,
        ObservationState state,
        DateTimeOffset renderedAt)
    {
        ArgumentNullException.ThrowIfNull(target);
        ArgumentNullException.ThrowIfNull(state);

        var sb = new StringBuilder();

        sb.Append("# ").AppendLine(FormatTitle(target.Name));
        sb.AppendLine();
        sb.Append("_Generated by the observation framework on ")
          .Append(renderedAt.UtcDateTime.ToString("yyyy-MM-dd HH:mm 'UTC'"))
          .AppendLine(".  ");
        sb.AppendLine("Manual edits to this file will be overwritten on the next dream cycle._");
        sb.AppendLine();

        AppendTheoriesSection(sb, state.Theories);
        sb.AppendLine();
        AppendCandidatesSection(sb, state.Candidates, target.PromotionThreshold);

        return sb.ToString();
    }

    private static void AppendTheoriesSection(StringBuilder sb, IReadOnlyList<Theory> theories)
    {
        sb.Append("## Theories (").Append(theories.Count).AppendLine(")");
        sb.AppendLine();

        if (theories.Count == 0)
        {
            sb.AppendLine("_No theories yet — observations are still accumulating._");
            return;
        }

        // Sort by reference count desc, then by promotion date asc for stable ordering.
        var ordered = theories
            .OrderByDescending(t => DistinctConversationCount(t.References))
            .ThenBy(t => t.PromotedAt)
            .ToList();

        foreach (var t in ordered)
        {
            var distinct = DistinctConversationCount(t.References);
            sb.Append("### ").AppendLine(t.Text.TrimEnd('.', ' ') + ".");
            sb.AppendLine();
            sb.Append("- **Reinforced:** ").Append(distinct).AppendLine(" conversation(s)");
            if (t.References.Count > 0)
            {
                var first = t.References.Min(r => r.ObservedAt);
                var last = t.References.Max(r => r.ObservedAt);
                sb.Append("- **First observed:** ").AppendLine(first.UtcDateTime.ToString("yyyy-MM-dd"));
                sb.Append("- **Last reinforced:** ").AppendLine(last.UtcDateTime.ToString("yyyy-MM-dd"));
                var representative = t.References
                    .OrderByDescending(r => r.ObservedAt)
                    .First();
                sb.Append("- **Representative quote:** ")
                  .Append('"')
                  .Append(Truncate(representative.Quote, 200))
                  .AppendLine("\"");
            }
            sb.AppendLine();
        }
    }

    private static void AppendCandidatesSection(StringBuilder sb, IReadOnlyList<Candidate> candidates, int promotionThreshold)
    {
        sb.Append("## Candidate observations (").Append(candidates.Count).AppendLine(")");
        sb.AppendLine();
        sb.Append("_Observations seen but not yet reinforced enough to promote.  ");
        sb.Append("Threshold: ").Append(promotionThreshold).AppendLine(" distinct conversation(s)._");
        sb.AppendLine();

        if (candidates.Count == 0)
        {
            sb.AppendLine("_(none)_");
            return;
        }

        var ordered = candidates
            .OrderByDescending(c => c.Count)
            .ThenBy(c => c.FirstSeen)
            .ToList();

        foreach (var c in ordered)
        {
            sb.Append("- **").Append(c.Text.TrimEnd('.', ' ')).Append("**");
            sb.Append("  (").Append(c.Count).Append(" conversation(s)");
            if (c.References.Count > 0)
            {
                var first = c.References.Min(r => r.ObservedAt);
                var last = c.References.Max(r => r.ObservedAt);
                sb.Append(", ").Append(first.UtcDateTime.ToString("yyyy-MM-dd"));
                if (last != first)
                    sb.Append(" → ").Append(last.UtcDateTime.ToString("yyyy-MM-dd"));
            }
            sb.AppendLine(")");
        }
    }

    private static int DistinctConversationCount(IReadOnlyList<ObservationReference> refs) =>
        refs.Select(r => r.ConversationId)
            .Distinct(StringComparer.Ordinal)
            .Count();

    private static string FormatTitle(string targetName)
    {
        // "theory-of-self" -> "Theory of self"
        var parts = targetName.Split('-');
        if (parts.Length == 0) return targetName;
        var head = parts[0];
        var headTitle = char.ToUpperInvariant(head[0]) + (head.Length > 1 ? head[1..] : string.Empty);
        return string.Join(' ', new[] { headTitle }.Concat(parts.Skip(1)));
    }

    private static string Truncate(string s, int max) =>
        s.Length <= max ? s : s[..max] + "…";
}
