# Binds the Script Manager's ServiceAccount to the rockbot-script-runner Role.
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rockbot-scripts-manager-script-runner
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "rockbot.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: rockbot-script-runner
subjects:
  - kind: ServiceAccount
    name: rockbot-scripts-manager
    namespace: {{ .Values.namespace }}
