{{- if .Values.staging.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "rockbot.stagingPvcName" . }}
  namespace: {{ .Values.namespace }}
  annotations:
    helm.sh/resource-policy: keep
  labels:
    {{- include "rockbot.labels" . | nindent 4 }}
    app.kubernetes.io/component: staging
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.storage.storageClass }}
  resources:
    requests:
      storage: {{ .Values.staging.size }}
{{- end }}
