namespace RockBot.Messaging;

/// <summary>
/// Well-known header keys and values for message envelope metadata.
/// </summary>
public static class WellKnownHeaders
{
    /// <summary>
    /// Indicates the trust level / provenance of the message content.
    /// </summary>
    public const string ContentTrust = "rb-content-trust";

    /// <summary>
    /// Identifies the tool provider backend (e.g. "mcp", "rest").
    /// </summary>
    public const string ToolProvider = "rb-tool-provider";

    /// <summary>
    /// Timeout in milliseconds for the tool invocation.
    /// </summary>
    public const string TimeoutMs = "rb-timeout-ms";

    /// <summary>
    /// JSON-encoded dictionary of caller claims that an upstream gateway has already
    /// verified (e.g. extracted from a validated JWT). Lets an inbound A2A message carry
    /// a cryptographically-verified identity so the agent's <c>IAgentIdentityVerifier</c>
    /// can mark the identity as not self-asserted, recording the IdP issuer and claims.
    /// The <c>rb-</c> prefix ensures it round-trips through the RabbitMQ AMQP header mapping.
    /// </summary>
    public const string AuthClaims = "rb-auth-claims";

    /// <summary>
    /// Known values for the <see cref="ContentTrust"/> header.
    /// </summary>
    public static class ContentTrustValues
    {
        /// <summary>Generated by the agent host itself (system prompts, internal directives).</summary>
        public const string System = "system";

        /// <summary>Content originating from a human user.</summary>
        public const string UserInput = "user-input";

        /// <summary>Outbound tool invocation request.</summary>
        public const string ToolRequest = "tool-request";

        /// <summary>Data returned from an external tool — UNTRUSTED.</summary>
        public const string ToolOutput = "tool-output";

        /// <summary>Content from another agent via A2A.</summary>
        public const string AgentMessage = "agent-message";
    }
}
