namespace RockBot.Messaging;

/// <summary>
/// Well-known header keys and values for message envelope metadata.
/// </summary>
public static class WellKnownHeaders
{
    /// <summary>
    /// Indicates the trust level / provenance of the message content.
    /// </summary>
    public const string ContentTrust = "rb-content-trust";

    /// <summary>
    /// Identifies the tool provider backend (e.g. "mcp", "rest").
    /// </summary>
    public const string ToolProvider = "rb-tool-provider";

    /// <summary>
    /// Timeout in milliseconds for the tool invocation.
    /// </summary>
    public const string TimeoutMs = "rb-timeout-ms";

    /// <summary>
    /// Known values for the <see cref="ContentTrust"/> header.
    /// </summary>
    public static class ContentTrustValues
    {
        /// <summary>Generated by the agent host itself (system prompts, internal directives).</summary>
        public const string System = "system";

        /// <summary>Content originating from a human user.</summary>
        public const string UserInput = "user-input";

        /// <summary>Outbound tool invocation request.</summary>
        public const string ToolRequest = "tool-request";

        /// <summary>Data returned from an external tool — UNTRUSTED.</summary>
        public const string ToolOutput = "tool-output";

        /// <summary>Content from another agent via A2A.</summary>
        public const string AgentMessage = "agent-message";
    }
}
