namespace RockBot.Host;

/// <summary>
/// An agent skill: a named markdown procedure document the LLM can read and follow.
/// </summary>
/// <param name="Name">
/// Identifier used to retrieve the skill, e.g. <c>plan-meeting</c> or <c>research/summarize</c>.
/// </param>
/// <param name="Summary">
/// One-line description shown in the skill index. Generated by the LLM in the background
/// after the skill is saved; may be empty while generation is in progress.
/// </param>
/// <param name="Content">Full markdown procedure content.</param>
public sealed record Skill(
    string Name,
    string Summary,
    string Content,
    DateTimeOffset CreatedAt,
    DateTimeOffset? UpdatedAt = null);
