namespace RockBot.Host;

/// <summary>
/// An agent skill: a named markdown procedure document the LLM can read and follow.
/// </summary>
/// <param name="Name">
/// Identifier used to retrieve the skill, e.g. <c>plan-meeting</c> or <c>research/summarize</c>.
/// </param>
/// <param name="Summary">
/// One-line description shown in the skill index. Generated by the LLM in the background
/// after the skill is saved; may be empty while generation is in progress.
/// </param>
/// <param name="Content">Full markdown procedure content.</param>
/// <param name="LastUsedAt">
/// When the skill was last loaded via <c>get_skill</c>, or <c>null</c> if it has never been used.
/// Used by the dream pass to prune skills that have not been accessed for an extended period.
/// </param>
/// <param name="SeeAlso">
/// Names of related skills the agent should consider alongside this one — sibling skills in the same
/// prefix cluster, commonly co-used skills, or logical complements. Populated by the dream
/// consolidation pass; <c>null</c> or empty if no cross-references have been established.
/// </param>
public sealed record Skill(
    string Name,
    string Summary,
    string Content,
    DateTimeOffset CreatedAt,
    DateTimeOffset? UpdatedAt = null,
    DateTimeOffset? LastUsedAt = null,
    IReadOnlyList<string>? SeeAlso = null);
